/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Sach;
import Service.BookService;
import Service.TypeBookService;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHAM_HUNG
 */
public class InPutUI extends javax.swing.JFrame {

    /**
     * Creates new form InPutUI
     */
    public InPutUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnRefresh = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnAddTypeBook = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        spListBook = new javax.swing.JScrollPane();
        tableListBook = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jckId = new javax.swing.JCheckBox();
        jckName = new javax.swing.JCheckBox();
        jckType = new javax.swing.JCheckBox();
        jckAuthor = new javax.swing.JCheckBox();
        jckAll = new javax.swing.JCheckBox();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemAddBook = new javax.swing.JMenuItem();
        menuItemAddType = new javax.swing.JMenuItem();
        menuItemDelete = new javax.swing.JMenuItem();
        menuItemEdit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AddBook");

        jToolBar1.setRollover(true);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/refresh-icon.jpg"))); // NOI18N
        btnRefresh.setText("Làm Mới");
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRefresh);

        btnAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/book-icon.png"))); // NOI18N
        btnAddBook.setText("Thêm Sách");
        btnAddBook.setFocusable(false);
        btnAddBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddBook);

        btnAddTypeBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/typebook-icon.png"))); // NOI18N
        btnAddTypeBook.setText("Loại Sách");
        btnAddTypeBook.setFocusable(false);
        btnAddTypeBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddTypeBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddTypeBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTypeBookActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddTypeBook);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete-icon.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/edit-icon.jpg"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEdit);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logout-icon copy.jpg"))); // NOI18N
        btnLogout.setText("Đăng Xuất");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        spListBook.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ListBook", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(237, 18, 18))); // NOI18N
        spListBook.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spListBook.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableListBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Type", "Author", "Publication date", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListBookMouseClicked(evt);
            }
        });
        spListBook.setViewportView(tableListBook);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        buttonGroup1.add(jckId);
        jckId.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jckId.setText("Mã Sách");

        buttonGroup1.add(jckName);
        jckName.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jckName.setText("Tên Sách");

        buttonGroup1.add(jckType);
        jckType.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jckType.setText("Loại Sách");

        buttonGroup1.add(jckAuthor);
        jckAuthor.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jckAuthor.setText("Tác Giả");

        buttonGroup1.add(jckAll);
        jckAll.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jckAll.setText("All");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jckId, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jckName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jckType, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jckAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jckAll, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jckId)
                    .addComponent(jckName)
                    .addComponent(jckAll)
                    .addComponent(jckAuthor)
                    .addComponent(jckType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSearch.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 0, 0));

        btnSearch.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/search-flat.png"))); // NOI18N
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuFile.setText("File");

        menuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        menuFile.add(menuItemLogout);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        menuEdit.setText("Edit");

        menuItemAddBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAddBook.setText("AddBook");
        menuEdit.add(menuItemAddBook);

        menuItemAddType.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAddType.setText("TypeBook");
        menuItemAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddTypeActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemAddType);

        menuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        menuItemDelete.setText("Delete");
        menuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeleteActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemDelete);

        menuItemEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemEdit.setText("Edit");
        menuEdit.add(menuItemEdit);

        jMenuBar1.add(menuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spListBook)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spListBook, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Đăng Nhập Thành Công !");
        DangNhap ui = new DangNhap();
        ui.main();
        this.dispose();
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void tableListBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListBookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableListBookMouseClicked

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        // TODO add your handling code here:
        ThemSach dialog = new ThemSach();
        dialog.main();
        this.loadData(new BookService().SelectAll());

    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData(new BookService().SelectAll());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddTypeBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTypeBookActionPerformed
        // TODO add your handling code here:
        ThemLoaiSach dialog = new ThemLoaiSach();
        dialog.main();
        this.loadData(new BookService().SelectAll());
    }//GEN-LAST:event_btnAddTypeBookActionPerformed

    private void menuItemAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddTypeActionPerformed
        // TODO add your handling code here:
        ThemLoaiSach dialog = new ThemLoaiSach();
        dialog.main();
        this.loadData(new BookService().SelectAll());
    }//GEN-LAST:event_menuItemAddTypeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (tableListBook.getSelectedRow() > -1) {
            int x = JOptionPane.showConfirmDialog(null, "Bạn Muốn Xóa?", "", JOptionPane.YES_NO_OPTION);
            if (x == 0) {
                BookService bs = new BookService();
                Vector<Sach> listBook = new BookService().SelectAll();

                if (bs.Delete(listBook.get(tableListBook.getSelectedRow()).getId())) {
                    JOptionPane.showMessageDialog(null, "Đã Xóa !");
                    this.loadData(new BookService().SelectAll());
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa Thất Bại !");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Không Có Mục Nào Được Chọn !");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (tableListBook.getSelectedRow() > -1) {
            SuaSach dialog = new SuaSach();
            dialog.main(tableListBook.getSelectedRow());
            this.loadData(new BookService().SelectAll());
        } else {
            JOptionPane.showMessageDialog(null, "Bạn Chưa Chọn Dòng Nào !");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Đã Đăng Xuất !");
        DangNhap ui = new DangNhap();
        ui.main();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (jckAuthor.isSelected()) {
            Vector<Sach> listBook = new BookService().searchBy("author", txtSearch.getText());
            if (listBook.size()>0) {
                this.loadData(listBook);
            } else {
                JOptionPane.showMessageDialog(null, "Không Tìm Thấy !");
            }
        } else if (jckId.isSelected()) {
            Vector<Sach> listBook = new BookService().searchBy("id", txtSearch.getText());
            if (listBook.size()>0) {
                this.loadData(listBook);
            } else {
                JOptionPane.showMessageDialog(null, "Không Tìm Thấy !");
            }
        } else if (jckName.isSelected()) {
            Vector<Sach> listBook = new BookService().searchBy("name", txtSearch.getText());
            if(listBook.size()>0){
                this.loadData(listBook);
            }
            else{
                JOptionPane.showMessageDialog(null, "Không Tìm Thấy !");
            }
        } else if (jckType.isSelected()) {
            Vector<Sach> listBook = new BookService().searchByIdType(new TypeBookService().search(txtSearch.getText()));
            if(listBook.size()>0){
                this.loadData(listBook);
            }
            else{
                JOptionPane.showMessageDialog(null, "Không Có Mục Nào !");
            }
        } else if (jckAll.isSelected()) {
            Vector<Sach> listBook = new BookService().searchByAll(txtSearch.getText());
            if(listBook.size()>0){
                this.loadData(listBook);
            }
            else{
                JOptionPane.showMessageDialog(null, "Không Có Mục Nào !");
            }
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void menuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeleteActionPerformed
        // TODO add your handling code here:
        if (tableListBook.getSelectedRow() > -1) {
            int x = JOptionPane.showConfirmDialog(null,"Bạn Muốn Xóa?", "", JOptionPane.YES_NO_OPTION);
            if (x == 0) {
                BookService bs = new BookService();
                Vector<Sach> listBook = new BookService().SelectAll();

                if (bs.Delete(listBook.get(tableListBook.getSelectedRow()).getId())) {
                    JOptionPane.showMessageDialog(null, "Xóa Thành Công !");
                    this.loadData(new BookService().SelectAll());
                } else {
                    JOptionPane.showMessageDialog(null, "Xóa Thất Bại !");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bạn Hãy Chọn 1 Dòng !");
        }
    }//GEN-LAST:event_menuItemDeleteActionPerformed

    //load data from database to table
    private void loadData(Vector<Sach> listBook) {
        //Vector<Book> listBook = new BookService().SelectAll();
        DefaultTableModel model = (DefaultTableModel) tableListBook.getModel();
        model.setNumRows(0);
        for (Sach book : listBook) {
            Vector<Object> object = new Vector<>();
            object.add(book.getId());
            object.add(book.getName());
            object.add(book.getPrice());
            object.add(TypeBookService.codeToName(book.getIdType()));
            object.add(book.getAuthor());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String dateInString = sdf.format(book.getPublicationDate());
            object.add(dateInString);
            object.add(book.getAmount());
            model.addRow(object);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InPutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InPutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InPutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InPutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InPutUI ui = new InPutUI();
                ui.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                ui.setLocationRelativeTo(null);
                
                ui.setVisible(true);
                ui.jckAll.setSelected(true);
                ui.loadData(new BookService().SelectAll());
                //ui.jckAll.setSelected(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnAddTypeBook;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JCheckBox jckAll;
    private javax.swing.JCheckBox jckAuthor;
    private javax.swing.JCheckBox jckId;
    private javax.swing.JCheckBox jckName;
    private javax.swing.JCheckBox jckType;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemAddBook;
    private javax.swing.JMenuItem menuItemAddType;
    private javax.swing.JMenuItem menuItemDelete;
    private javax.swing.JMenuItem menuItemEdit;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JScrollPane spListBook;
    private javax.swing.JTable tableListBook;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
